---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: 'La dashboard ben progettata di NetApp Console analizza le configurazioni di sistema in termini di affidabilità, sicurezza, eccellenza operativa, ottimizzazione dei costi ed efficienza delle prestazioni, fornendo approfondimenti e raccomandazioni per aiutarti a raggiungere l"eccellenza operativa.' 
---
= Scopri la dashboard ben progettata in NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
La dashboard ben progettata di NetApp Console ti aiuta a mantenere e gestire configurazioni affidabili, sicure, efficienti e convenienti che sono in linea con i framework ben progettati per il tipo di storage che usi. La dashboard offre una visione unificata tra account e regioni, aiuta i team a identificare e dare priorità ai rischi e supporta regole personalizzate per requisiti specifici. Le scansioni automatiche giornaliere delle configurazioni del tuo sistema storage forniscono informazioni e suggerimenti per aiutarti a ottimizzare i tuoi ambienti di storage.



[[how-it-works]]
== Come funziona

La dashboard well-architected analizza quotidianamente le tue configurazioni. L'analisi fornisce stato well-architected, approfondimenti e raccomandazioni.

Al termine dell'analisi giornaliera, le configurazioni vengono visualizzate come "ottimizzate" o "non ottimizzate" nella dashboard di well-architected. Trovi il punteggio totale di ottimizzazione, i problemi di configurazione per categoria e un elenco di problemi di configurazione e raccomandazioni. Puoi rivedere le raccomandazioni per i problemi di configurazione. Alcuni problemi possono essere risolti automaticamente dalla dashboard di well-architected, mentre altri richiedono un intervento manuale. In questo caso, la dashboard di well-architected ti fornisce istruzioni dettagliate per aiutarti a implementare le modifiche consigliate.

Puoi ignorare l'analisi delle configurazioni che non si applicano ai tuoi ambienti. Questo evita avvisi non necessari e risultati di ottimizzazione imprecisi. Quando ignori l'analisi di una configurazione specifica, la well-architected dashboard non include la configurazione nel punteggio totale di ottimizzazione.



[[why-it-matters]]
== Perché è importante

La dashboard ben strutturata di NetApp Console applica le best practice ad ampi ambienti di storage, database e VMware, combinando la valutazione continua con suggerimenti e interventi correttivi. La correzione automatizzata applicata nella dashboard ben strutturata riduce gli errori umani, garantisce una gestione uniforme e preserva prestazioni e affidabilità nelle tue infrastrutture di sistema.



[[supported-storage-systems]]
== Sistemi storage supportati

La dashboard ben progettata nella Console supporta i seguenti sistemi storage:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP in Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Inizia a usare NetApp Console per rilevare e correggere le configurazioni errate del sistema

Per iniziare a utilizzare NetApp Console, registrati, aggiungi le credenziali e stabilisci la connettività per gestire le tue risorse e ottimizzare le configurazioni di sistema.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flusso di lavoro iniziale per NetApp Console (applicazione SaaS)"^]



[[related-information]]
== Informazioni correlate

* link:fsx/improve-configurations-fsx.html["Implementare FSx ben architettato per i file system ONTAP"^]
* link:cvo/improve-configurations-cvo.html["Implementa sistemi Cloud Volumes ONTAP ben progettati"^]

