---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: 'La dashboard ben progettata di NetApp Console analizza le configurazioni di sistema in termini di affidabilità, sicurezza, eccellenza operativa, ottimizzazione dei costi ed efficienza delle prestazioni, fornendo approfondimenti e raccomandazioni per aiutarti a raggiungere l"eccellenza operativa.' 
---
= Scopri la dashboard ben progettata in NetApp Console
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory ti aiuta a mantenere e gestire configurazioni affidabili, sicure, efficienti e convenienti, in linea con i framework ben strutturati per il tipo di storage che utilizzi. La dashboard ben strutturata nella NetApp Console offre una visione unificata tra account e regioni, aiuta i team a identificare e dare priorità ai rischi e supporta regole personalizzate per requisiti specifici. Le scansioni giornaliere automatiche delle configurazioni del tuo sistema storage forniscono informazioni e raccomandazioni per aiutarti a ottimizzare i tuoi ambienti di storage.



[[how-it-works]]
== Come funziona

Workload Factory analizza quotidianamente le tue configurazioni. L'analisi fornisce stato ben architettato, approfondimenti e raccomandazioni per aiutarti a ottimizzare i tuoi ambienti di storage.

Al termine dell'analisi giornaliera, le configurazioni vengono visualizzate come "ottimizzate" o "non ottimizzate" nella dashboard Well-Architected. Troverai i problemi di configurazione suddivisi per categoria del framework Well-Architected (affidabilità, sicurezza, eccellenza operativa, ottimizzazione dei costi ed efficienza delle prestazioni) e un elenco di problemi di configurazione e raccomandazioni. Workload Factory può risolvere alcuni problemi automaticamente, mentre altri richiedono un intervento manuale. In questo caso, la raccomandazione fornisce istruzioni dettagliate per aiutarti a implementare le modifiche.

Puoi ignorare l'analisi delle configurazioni che non si applicano ai tuoi ambienti. Ignorare le configurazioni evita avvisi inutili e risultati di ottimizzazione imprecisi.



[[why-it-matters]]
== Perché è importante

Workload Factory applica le best practice ad ambienti di storage, database e VMware di grandi dimensioni, combinando valutazioni continue con suggerimenti e interventi correttivi. La correzione automatizzata riduce gli errori umani, garantisce una gestione uniforme e preserva prestazioni e affidabilità nelle tue infrastrutture di sistema.



[[supported-storage-systems]]
== Sistemi storage supportati

La dashboard ben progettata nella Console supporta i seguenti sistemi storage:

* Amazon FSx for NetApp ONTAP
* Cloud Volumes ONTAP in Microsoft Azure




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== Inizia a usare NetApp Console per rilevare e correggere le configurazioni errate del sistema

Per iniziare a utilizzare NetApp Console, registrati, aggiungi le credenziali e stabilisci la connettività per gestire le tue risorse e ottimizzare le configurazioni di sistema.

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Flusso di lavoro iniziale per NetApp Console (applicazione SaaS)"^]



[[related-information]]
== Informazioni correlate

* link:fsx/improve-configurations-fsx.html["Implementare FSx ben architettato per i file system ONTAP"^]
* link:cvo/improve-configurations-cvo.html["Implementa sistemi Cloud Volumes ONTAP ben progettati"^]

