= 20 luglio 2026
:allow-uri-read: 


permalink: whats-new.html parole chiave: novità, funzionalità, nuovo, note di rilascio, miglioramenti, correzioni, nuove funzionalità, well-architected, dashboard well-architected, amazon fsx per netapp ontap, fsx per ontap, cloud volumes ontap riepilogo: "Scopri le novità della dashboard well-architected in NetApp Console." --- = Novità della dashboard Well-Architected in NetApp Console :icons: font :imagesdir: ./media/

[role="lead"]
Scopri le novità del componente Well-architected di Workload Factory.

Scopri le novità della dashboard Well-Architected in NetApp Console.



[[20-july-2026]]
== 20 luglio 2026



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== Presentazione della dashboard ben progettata in NetApp Console

La dashboard ben strutturata di NetApp Console offre una visione unificata dei tuoi sistemi storage e delle configurazioni su tutti gli account e le regioni. La dashboard fornisce informazioni e raccomandazioni per aiutarti a raggiungere l'eccellenza operativa. Puoi visualizzare lo stato ben strutturato delle tue configurazioni, i problemi di configurazione organizzati in base ai pilastri del framework ben strutturato per il tipo di storage che utilizzi e un elenco di problemi di configurazione e raccomandazioni.

Scopri di più su link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["dashboard ben progettata"].

La dashboard ben progettata nella Console è disponibile per i seguenti sistemi storage:

* link:https://docs.netapp.com/us-en/console-well-architected/configuration-analysis-fsx.html["Amazon FSx for NetApp ONTAP"]
* link:https://docs.netapp.com/us-en/console-well-architected/configuration-analysis-cvo.html["Cloud Volumes ONTAP in Microsoft Azure"]




[[build-your-own-custom-rules]]
=== Crea le tue regole personalizzate

Scrivi regole personalizzate in linguaggio semplice per assicurarti che i tuoi sistemi rispettino gli standard della tua organizzazione e le best practice di NetApp. Testa le regole con una simulazione, poi pianifica che vengano eseguite su tutti i tuoi ambienti.

https://docs.netapp.com/us-en/workload-well-architected/learn-custom-rules.html["Scopri di più sulle regole personalizzate"^]
