= Correggi, ignora e riattiva le configurazioni per Cloud Volumes ONTAP in Microsoft Azure
:allow-uri-read: 




[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== Correggi, ignora e riattiva le configurazioni per Cloud Volumes ONTAP in Microsoft Azure

La dashboard ben progettata di NetApp Console ora ti permette di correggere i suggerimenti di configurazione per i tuoi sistemi Cloud Volumes ONTAP.

Puoi anche escludere una o più configurazioni dall'analisi well-architected. Questo ti permette di ignorare configurazioni specifiche che non si applicano al tuo ambiente.

Se in seguito vuoi includere una configurazione precedentemente scartata, puoi riattivarla nella dashboard well-architected. Questo ripristina la configurazione nell'analisi e ti permette di ottenere suggerimenti e correzioni per essa.

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["Correggi, ignora e riattiva le configurazioni per Cloud Volumes ONTAP in Microsoft Azure"]
