---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: La dashboard ben progettata analizza regolarmente le configurazioni del file system FSx for ONTAP per individuare eventuali problemi di configurazione. 
---
= Analisi della configurazione per Amazon FSx per NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La dashboard ben progettata di NetApp Console analizza regolarmente le configurazioni del sistema storage per determinare se ci sono problemi di configurazione nei tuoi file system Amazon FSx for NetApp ONTAP. Quando vengono rilevati problemi, la dashboard ti mostra quali sono e spiega cosa deve essere cambiato per assicurare che i tuoi sistemi storage raggiungano prestazioni ottimali, efficienza dei costi e conformità alle best practice.

Le principali funzionalità includono:

* Analisi della configurazione giornaliera
* Validazioni automatiche delle best practice per i sistemi storage NetApp ONTAP e i provider di storage partner
* Osservabilità proattiva
* Dagli insight all'azione


Direttiva non risolta in <stdin> - include::well-architected-workloads.adoc[]



[[analysis-requirements]]
== Requisiti di analisi

Per un'analisi completa del file system, devi fare quanto segue:

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["Distribuisci un agente della NetApp Console"^] o link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["associa un collegamento"^] per configurare la connettività tra il file system e NetApp Console.
* Concedi le autorizzazioni di _visualizzazione, pianificazione e analisi_ nel tuo account AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Scopri come concedere le autorizzazioni a un account AWS"^]



Direttiva non risolta in <stdin> - include::fsx-configurations.adoc[]

.Cosa c'è dopo
link:improve-configurations-fsx.html["Implementa configurazioni ben architettate del file system FSx for ONTAP"]
